version: '3.1'

services:
  db:
    image: postgres:16.0-alpine
    restart: always
    ports:
      ["7995:5432"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: alcalarsuitedb
    volumes:
      - ./container/docker/postgres:/var/lib/postgresql/data