import { MigrationInterface, QueryRunner } from "typeorm";

export class PersonasV2AndUsuariosV11698799735705 implements MigrationInterface {
    name = 'PersonasV2AndUsuariosV11698799735705'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "T_USUARIOS" ("C_ID" SERIAL NOT NULL, "C_USUARIO" character varying(50) NOT NULL, "C_PASSWORD" character varying(100) NOT NULL, "C_ROLES" text array NOT NULL DEFAULT '{USER}', "C_ESTADO" character varying(1) NOT NULL DEFAULT 'A', "C_ANOTACIONES" character varying(1000), "C_FECHA_CREACION" date, "C_USUARIO_CREO" character varying(30), "C_FECHA_ACTUALIZACION" date, "C_USUARIO_ACTUALIZO" character varying(30), "C_PERSON_FK" integer, CONSTRAINT "UQ_d0531366d2dfebd32ade061b107" UNIQUE ("C_USUARIO"), CONSTRAINT "REL_4a708e898c0facf2cec6dd1a7f" UNIQUE ("C_PERSON_FK"), CONSTRAINT "PK_ad30ba64d5be9282d9349137bd4" PRIMARY KEY ("C_ID")); COMMENT ON COLUMN "T_USUARIOS"."C_ID" IS 'PK numérica autogenerada para tabla usuarios'; COMMENT ON COLUMN "T_USUARIOS"."C_USUARIO" IS 'Username del usuario'; COMMENT ON COLUMN "T_USUARIOS"."C_PASSWORD" IS 'Contraseña del usuario'; COMMENT ON COLUMN "T_USUARIOS"."C_ROLES" IS 'Roles del Usuario'; COMMENT ON COLUMN "T_USUARIOS"."C_ESTADO" IS 'Estado columna de base de datos'; COMMENT ON COLUMN "T_USUARIOS"."C_ANOTACIONES" IS 'Anotaciones adicionales del usuario'; COMMENT ON COLUMN "T_USUARIOS"."C_FECHA_CREACION" IS 'Fecha Creación de la row'; COMMENT ON COLUMN "T_USUARIOS"."C_USUARIO_CREO" IS 'Documento Usuario que creo la row'; COMMENT ON COLUMN "T_USUARIOS"."C_FECHA_ACTUALIZACION" IS 'Fecha Actualización de la row'; COMMENT ON COLUMN "T_USUARIOS"."C_USUARIO_ACTUALIZO" IS 'Documento Usuario que actualizó la row'; COMMENT ON COLUMN "T_USUARIOS"."C_PERSON_FK" IS 'PK numérica autogenerada para tabla personas'`);
        await queryRunner.query(`CREATE TABLE "T_PERSONAS" ("C_ID" SERIAL NOT NULL, "C_NUMERO_DOCUMENTO" character varying(50) NOT NULL, "C_TIPO_DOCUMENTO" character varying(50) NOT NULL, "C_NOMBRES" character varying(150) NOT NULL, "C_APELLIDOS" character varying(150) NOT NULL, "C_TELEFONO_FIJO" character varying(30), "C_TELEFONO_MOVIL" character varying(30) NOT NULL, "C_EMAIL" character varying(150) NOT NULL, "C_DIRECCION_RESIDENCIA" character varying(150), "C_NACIMIENTO" date, "C_GENERO" character varying(1) NOT NULL DEFAULT 'M', "C_ANOTACIONES" character varying(1000), "C_ESTADO" character varying(1) NOT NULL DEFAULT 'A', "C_FECHA_CREACION" date, "C_USUARIO_CREO" character varying(30), "C_FECHA_ACTUALIZACION" date, "C_USUARIO_ACTUALIZO" character varying(30), CONSTRAINT "UQ_a2f3f9b74c38b6de79247518003" UNIQUE ("C_NUMERO_DOCUMENTO"), CONSTRAINT "UQ_e33a637b16ce6d3321490c72b49" UNIQUE ("C_EMAIL"), CONSTRAINT "PK_5f50be5cb9eaccc8885c127fab1" PRIMARY KEY ("C_ID")); COMMENT ON COLUMN "T_PERSONAS"."C_ID" IS 'PK numérica autogenerada para tabla personas'; COMMENT ON COLUMN "T_PERSONAS"."C_NUMERO_DOCUMENTO" IS 'Número de documento de identidad'; COMMENT ON COLUMN "T_PERSONAS"."C_TIPO_DOCUMENTO" IS 'Tipo de documento de identidad'; COMMENT ON COLUMN "T_PERSONAS"."C_NOMBRES" IS 'Nombres de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_APELLIDOS" IS 'Apellidos de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_TELEFONO_FIJO" IS 'Teléfono Fíjo de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_TELEFONO_MOVIL" IS 'Teléfono Móvil de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_EMAIL" IS 'Correo Electrónico de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_DIRECCION_RESIDENCIA" IS 'Dirección Residencial de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_NACIMIENTO" IS 'Nacimiento de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_GENERO" IS 'Género de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_ANOTACIONES" IS 'Anotaciones adicionales de la persona'; COMMENT ON COLUMN "T_PERSONAS"."C_ESTADO" IS 'Estado columna de base de datos'; COMMENT ON COLUMN "T_PERSONAS"."C_FECHA_CREACION" IS 'Fecha Creación de la row'; COMMENT ON COLUMN "T_PERSONAS"."C_USUARIO_CREO" IS 'Documento Usuario que creo la row'; COMMENT ON COLUMN "T_PERSONAS"."C_FECHA_ACTUALIZACION" IS 'Fecha Actualización de la row'; COMMENT ON COLUMN "T_PERSONAS"."C_USUARIO_ACTUALIZO" IS 'Documento Usuario que actualizó la row'`);
        await queryRunner.query(`ALTER TABLE "T_USUARIOS" ADD CONSTRAINT "FK_T_PERSONAS" FOREIGN KEY ("C_PERSON_FK") REFERENCES "T_PERSONAS"("C_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "T_USUARIOS" DROP CONSTRAINT "FK_T_PERSONAS"`);
        await queryRunner.query(`DROP TABLE "T_PERSONAS"`);
        await queryRunner.query(`DROP TABLE "T_USUARIOS"`);
    }

}
